const shopCatalog = {
  Fire: [
    { id: 4, name: 'Charmander', types: ['fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 400, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] },
    { id: 5, name: 'Charmeleon', types: ['fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] },
    { id: 6, name: 'Charizard', types: ['fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] },
    { id: 37, name: 'Vulpix', types: ['fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] },
    { id: 38, name: 'Ninetales', types: ['fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] },
    { id: 58, name: 'Growlithe', types: ['fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] },
    { id: 59, name: 'Arcanine', types: ['fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] },
    { id: 77, name: 'Ponyta', types: ['fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] },
    { id: 78, name: 'Rapidash', types: ['fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] },
    { id: 126, name: 'Magmar', types: ['fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] }
  ],
  Water: [
    { id: 7, name: 'Squirtle', types: ['water'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png', maxMana: 100, mana: 100, armor: 100, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 8, name: 'Wartortle', types: ['water'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png', maxMana: 100, mana: 100, armor: 100, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 9, name: 'Blastoise', types: ['water'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png', maxMana: 100, mana: 100, armor: 100, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 54, name: 'Psyduck', types: ['water'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png', maxMana: 100, mana: 100, armor: 100, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 55, name: 'Golduck', types: ['water'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png', maxMana: 100, mana: 100, armor: 100, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 60, name: 'Poliwag', types: ['water'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png', maxMana: 100, mana: 100, armor: 100, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 61, name: 'Poliwhirl', types: ['water'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png', maxMana: 100, mana: 100, armor: 100, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 62, name: 'Poliwrath', types: ['water'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png', maxMana: 100, mana: 100, armor: 100, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 72, name: 'Tentacool', types: ['water'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png', maxMana: 100, mana: 100, armor: 100, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 73, name: 'Tentacruel', types: ['water'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png', maxMana: 100, mana: 100, armor: 100, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] }
  ],
  Normal: [
    { id: 19, name: 'Rattata', types: ['normal'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 20, name: 'Raticate', types: ['normal'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 16, name: 'Pidgey', types: ['normal'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 17, name: 'Pidgeotto', types: ['normal'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 18, name: 'Pidgeot', types: ['normal'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 21, name: 'Spearow', types: ['normal'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 22, name: 'Fearow', types: ['normal'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 83, name: 'Farfetch\'d', types: ['normal'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 84, name: 'Doduo', types: ['normal'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 85, name: 'Dodrio', types: ['normal'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] }
  ],
  Poison: [
    { id: 1, name: 'Bulbasaur', types: ['grass','poison'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 2, name: 'Ivysaur', types: ['grass','poison'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 3, name: 'Venusaur', types: ['grass','poison'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 23, name: 'Ekans', types: ['poison'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 24, name: 'Arbok', types: ['poison'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 29, name: 'Nidoran♀', types: ['poison'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 30, name: 'Nidorina', types: ['poison'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 31, name: 'Nidoqueen', types: ['poison'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 32, name: 'Nidoran♂', types: ['poison'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 33, name: 'Nidorino', types: ['poison'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] }
  ],
  Dragon: [
    { id: 147, name: 'Dratini', types: ['dragon'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 148, name: 'Dragonair', types: ['dragon'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 149, name: 'Dragonite', types: ['dragon'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Vine Whip', mana: 0, power: 40, cd: 0, desc: 'Basic grass whip' }, { name: 'Razor Leaf', mana: 20, power: 60, cd: 2, desc: 'Sharp leaf barrage' }, { name: 'Poison Powder', mana: 35, power: 20, cd: 4, desc: 'Applies poison DOT' }, { name: 'Bloom Doom', mana: 60, power: 130, cd: 10, desc: 'ULT: massive plant eruption' }] },
    { id: 130, name: 'Gyarados', types: ['water','flying'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 6, name: 'Mega-Charizard X', types: ['dragon','fire'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Scratch', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Ember', mana: 20, power: 60, cd: 2, desc: 'Low-cost fire spit' }, { name: 'Flame Burst', mana: 35, power: 80, cd: 4, desc: 'Small AoE burst' }, { name: 'Inferno Overdrive', mana: 60, power: 130, cd: 10, desc: 'ULT: huge fire blast' }] },
    { id: 329, name: 'Trapinch', types: ['ground'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/329.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 330, name: 'Vibrava', types: ['ground','dragon'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/330.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 331, name: 'Flygon', types: ['ground','dragon'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/331.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 246, name: 'Larvitar', types: ['rock','ground'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/246.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] },
    { id: 247, name: 'Pupitar', types: ['rock','ground'], sprite: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/247.png', maxMana: 100, mana: 100, armor: 0, moves: [{ name: 'Tackle', mana: 0, power: 40, cd: 0, desc: 'Basic attack' }, { name: 'Water Gun', mana: 20, power: 60, cd: 2, desc: 'Ranged water shot' }, { name: 'Aqua Tail', mana: 35, power: 80, cd: 4, desc: 'Strong tail whip' }, { name: 'Hydro Vortex', mana: 60, power: 130, cd: 10, desc: 'ULT: crushing water vortex' }] }
  ]
};

const allFighters = Object.values(shopCatalog).flat();

window.getMyFighters = function() {
  const raw = localStorage.getItem('owned') || '';
  let ownedIds = [];

  try {
    const obj = JSON.parse(raw);
    if (Array.isArray(obj?.fighters)) ownedIds = obj.fighters;
  } catch (e) {
    const match = raw.match(/^fighters:(.+)$/);
    if (match) ownedIds = match[1].split(',').map(Number);
  }

  return allFighters.filter(f => ownedIds.includes(f.id));
};

// Expose the one thing that choose.js and battlesystem.js definitely expect
window.allFighters = allFighters;

console.log(`catalog.js → ${allFighters.length} fighters loaded & exposed globally as window.allFighters`);